import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LandingPageNavbar from "@/components/common/LandingPageNavbar";
import { cookies } from "next/headers";
import jwt, { JwtPayload } from "jsonwebtoken";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/Logo.png",
  },
};

interface AppJwtPayload extends JwtPayload {
  fullName?: string;
  avatar?: string;
}

// 1. Hàm này phải là ASYNC vì cookies() trả về Promise trong Next.js 15
async function getCurrentUser() {
  // 2. Phải await cookies() trước khi .get()
  const cookieStore = await cookies();
  const token = cookieStore.get("accessToken")?.value;

  if (!token) return null;

  try {
    const decoded = jwt.decode(token) as AppJwtPayload | null;
    if (!decoded) return null;

    return {
      name: decoded.fullName || null,
      image: decoded.avatar || null,
    };
  } catch (err) {
    console.error("Failed to decode JWT:", err);
    return null;
  }
}

// 3. Layout cũng phải là ASYNC để await được getCurrentUser
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <LandingPageNavbar user={user} />
        <main className="min-h-screen pt-14">{children}</main>
      </body>
    </html>
  );
}
